const categoriesTypes = {
  ADD_NEW_CATEGORY_START: 'ADD_NEW_CATEGORY_START',
  EDIT_NEW_CATEGORY_START: 'EDIT_NEW_CATEGORY_START',
  FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
  SET_CATEGORIES: 'SET_CATEGORIES',
  DELETE_CATEGORIES_START: 'DELETE_CATEGORIES_START',
  FETCH_CATEGORY_START: 'FETCH_CATEGORY_START',
  SET_CATEGORY: 'SET_CATEGORY',
};

export default categoriesTypes;